font_family      FiraMono Nerd Font Mono
bold_font        FiraMono Nerd Font Mono Bold
italic_font      FiraMono Nerd Font Mono Italic
bold_italic_font FiraMono Nerd Font Mono Bold Italic

font_size 9.0

include themes/dist/rose-pine.conf

window_padding_width 5
