#GLX 
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = true;
xrender-sync-fence = "true";
glx-swap-method = -1;

#Shadows

shadow = false;
shadow-radius = 13;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = .5;
shadow-ignore-shaped = false;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
];

wintypes:
{
  dock = { shadow = true; }
  dnd = { shadow = true; }
  popup_menu = { opacity = 1.0; }
  dropdown_menu = { opacity = 1.0; }
}

#Corners

corner-radius = 10;
round-borders = 10;
	
rounded-corners-exclude = [
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'popup'",
  "class_g = 'Polybar'",
  "class_g = 'Eww-bar'",
  "class_g = 'Rofi'",

];
