#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10

bspc config normal_border_color "#a9b1d6"
bspc config focused_border_color "#c0caf5"
bspc config urgent_border_color "#f7768e"
bspc config presel_border_color "#9ece6a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap latam 
feh --bg-scale /home/farnese/Wallpapers/13.jpg &
picom &
polybar principal &
wmname LG3D &
