[colors]
background = #191724
background-alt = #21202e
foreground = #e0def4
primary = #ebbcba
secondary = #f6c177
alert = #eb6f92
disabled = #6e6a86

[bar/general]
width = 100%
height = 25pt
radius = 8

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 5pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 2

separator = " "
separator-foreground = ${colors.foreground}

font-0 = "FiraMono Nerd Font:pixelsize=9;0"

cursor-click = pointer
cursor-scroll = ns-resize

wm-restack = bspwm

[bar/principal]
inherit = bar/general

bottom = true

modules-left = xworkspaces
modules-center = date
modules-right = cosas day volumen tray teclado
background = ${colors.background}

width = 100%

[module/bspwm]
type = internal/bspwm

label-focused = %icon%
label-focused-foreground = ${colors.primary}
label-focused-underline = ${colors.disabled}
label-focused-padding = 2

label-occupied = %icon%
label-occupied-padding = 2
label-occupied-foreground = ${colors.secondary}

label-urgent = %icon%
label-urgent-foreground = ${colors.alert}
label-urgent-padding = 2

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 2

label-separator =   

[module/date]
type = internal/date
interval = 1
date = %I:%M %p
label =   %date%

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/cosas]
type = internal/xwindow
label =   %title:0:60:...%

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/teclado]
type = internal/xkeyboard
padding-right = 3
padding = 2
blacklist-0 = num lock
blacklist-1 = scroll lock

background-color = &{colors.alert}

label-layout =   %layout%
label-layout-underline = ${colors.none}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.background}
label-indicator-underline = ${colors.none}
label-right-padding = 5
label = 

[module/tray]
type = internal/tray
spacing = 1
padding-left = 5
padding-right = 5
padding = 2
background = ${colors.background}
foreground = ${colors.foreground}
icon-size = 15

[module/day]
type = custom/script
interval = 600
format-prefix = 
format-prefix-foreground = ${colors.foreground}
format-foreground = ${colors.foreground}
exec = /home/farnese/.config/polybar/day.sh
label =   %output%

[module/volumen]
type = internal/pulseaudio

; Definir el formato general del módulo
format = #  %volume%%{A4:pactl set-sink-mute @DEFAULT_SINK@ toggle:}%togglemute%%{A}%{A5:pactl set-sink-volume @DEFAULT_SINK@ +5%:}%increasevol%%{A}%{A3:pactl set-sink-volume @DEFAULT_SINK@ -5%:}%decreasevol%%{A}

; Definir el formato del indicador de volumen
label-format = %percentage%
label-indicator-padding = 2

[module/reload]
type = custom/script
interval = 1
exec = /home/farnese/.config/polybar/reload.sh

; Formato del módulo
format = %output%
